server:
  port: 9000
# ???? ?? ??? 9000??
# BasicControllerApplication? ???? 9000? ??? ???.
spring:
  mustache:
    servlet:
      expose-request-attributes: true
      expose-session-attributes: true
      #request? session? ???? ?.
    #default??? templates??
